---
title: "Pakistan CCDR - 04. Sectoral Interventions for Green, Resilient and Inclusive Development"
date: "2/22/2022"
output:
  html_document: default
---

This chapter will identify the key sectoral policy and institutional shifts needed to reduce exposure to climate change risks, physical and transition related, and accelerate the decarbonization of the economy. The climate change impacts that Pakistan is already facing, and the projected intensification of these risks, underscores the need for an immediate focus on building resilience to protect the country from the most severe impacts of a changing climate.

### Required packages and settings

```{r, results='hide', message=FALSE}
source("../styles/CCDR_basic_style.R")
source("../styles/SDG_atlas_styles.R")
source("../utils/CCDR_utils.R")
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggalt)
library(forcats)
library(png)
library(ggpubr)
library(scales)
library(hrbrthemes)
library(viridis)
library(wbstats)
library(wbgcharts)
library(wbgmaps)
library(wbggeo)
library(readr)
library(readxl)
library(gtable)
library(grid)
library(lubridate)
library(extrafont)
# this only needs to be done once
# library(remotes)
# remotes::install_version("Rttf2pt1", version = "1.3.8")
# font_import() 
# loadfonts(device = 'win')
create_wbgref()
```


## 4.1	Promoting Low-Emission and Resilient Agriculture and Land Use for Food and Water Security 



## 4.2	The Energy Transition (Abed: 3 pages. with inputs from Energy team, transport team and IFC and FCI



## 4.3	Industrial Decarbonization (Abed: 3 pages. with inputs from Energy team, transport team and IFC and FCI



## 4.4  Building Resilient and Livable Cities  




