---
title: "Pakistan CCDR - 05. The Macro-Fiscal, Financial and Distributional Impacts of Climate and Development Policy Actions"
date: "2/22/2022"
output:
  html_document: default
---

This chapter will evaluate the macro-fiscal, financial and distributional implications of scaling up key sectoral actions, with a focus on impacts on growth, employment, poverty reduction, health and human development, fiscal and financial feasibility and macro-fiscal and financial stability. The global climate scenarios used in chapter 3 will also frame this analysis. The policy actions to be considered will assess alternative pathways to build resilience to climate risk and reduce emissions in directions which are synergistic with progress on immediate development needs. The policy packages to be assessed focus on planned actions under the revised NDC for Pakistan and other existing climate policies and investments. Additional pathways may consider more ambitious actions to build resilience and/or reduce emissions, as well as a pathway that shifts the short and medium term emphasis towards addressing Pakistan’s critical human development challenges while also investing in urgent resilience needs. These more ambitious pathways will be covered, as far as is feasible within the timeline of the CCDR, drawing on the policy actions that emerge from the analysis done in Chapter 4.  The analysis will use a range of macro-econometric models (MFMod, E3Me, CPAT) to look at specific policy actions. In each case, the distributional impact will be assessed by combining microsimulation techniques with the macro models.

### Required packages and settings

```{r, results='hide', message=FALSE}
source("../styles/CCDR_basic_style.R")
source("../styles/SDG_atlas_styles.R")
source("../utils/CCDR_utils.R")
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggalt)
library(forcats)
library(png)
library(ggpubr)
library(scales)
library(hrbrthemes)
library(viridis)
library(wbstats)
library(wbgcharts)
library(wbgmaps)
library(wbggeo)
library(readr)
library(readxl)
library(gtable)
library(grid)
library(lubridate)
library(extrafont)
# this only needs to be done once
# library(remotes)
# remotes::install_version("Rttf2pt1", version = "1.3.8")
# font_import() 
# loadfonts(device = 'win')
create_wbgref()
```


## 5.1	Policy pathways to build resilience to climate risks and reduce emissions



